{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bytedance.android",
    "module": "aabresguard-plugin",
    "version": "0.1.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "slmwxe3c7rad7cjwpbnogrbfli"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.bytedance.android",
          "module": "aabresguard-core",
          "version": {
            "requires": "0.1.10"
          },
          "excludes": [
            {
              "group": "com.android.tools.build",
              "module": "bundletool"
            },
            {
              "group": "com.google.guava",
              "module": "guava"
            },
            {
              "group": "com.android.tools.build",
              "module": "gradle"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "aabresguard-plugin-0.1.10.jar",
          "url": "aabresguard-plugin-0.1.10.jar",
          "size": 21251,
          "sha512": "3acb65e6672caacd53b3bceb6dc78418cf65f6d9b1d2c27654e467e9ced8e2523166e802cd85126cbbe0cd4266df4093c15ff4a0ac2eab0bc2b5709b9fb1a840",
          "sha256": "93d361228705263069eb6bcbe0e6ab52a76a2a4a8f7fb146ebe74ee959712fe5",
          "sha1": "a9705cf926c2356b63bf7d57ec940f230bddb3d8",
          "md5": "1e7f125c3b2151aba2230302b193de1f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.3.61"
          },
          "excludes": [
            {
              "group": "com.android.tools.build",
              "module": "bundletool"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.3.61"
          },
          "excludes": [
            {
              "group": "com.android.tools.build",
              "module": "bundletool"
            }
          ]
        },
        {
          "group": "com.bytedance.android",
          "module": "aabresguard-core",
          "version": {
            "requires": "0.1.10"
          },
          "excludes": [
            {
              "group": "com.android.tools.build",
              "module": "bundletool"
            },
            {
              "group": "com.google.guava",
              "module": "guava"
            },
            {
              "group": "com.android.tools.build",
              "module": "gradle"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "aabresguard-plugin-0.1.10.jar",
          "url": "aabresguard-plugin-0.1.10.jar",
          "size": 21251,
          "sha512": "3acb65e6672caacd53b3bceb6dc78418cf65f6d9b1d2c27654e467e9ced8e2523166e802cd85126cbbe0cd4266df4093c15ff4a0ac2eab0bc2b5709b9fb1a840",
          "sha256": "93d361228705263069eb6bcbe0e6ab52a76a2a4a8f7fb146ebe74ee959712fe5",
          "sha1": "a9705cf926c2356b63bf7d57ec940f230bddb3d8",
          "md5": "1e7f125c3b2151aba2230302b193de1f"
        }
      ]
    }
  ]
}
